// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgW3Tp8pd2jX6iLZ983NofJfLhkEDaFj8',
    appId: '1:543256822391:web:c0368050b80537c244fc72',
    messagingSenderId: '543256822391',
    projectId: 'women-safety-app-30676',
    authDomain: 'women-safety-app-30676.firebaseapp.com',
    storageBucket: 'women-safety-app-30676.firebasestorage.app',
    measurementId: 'G-ZXBQ3PGZ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchfRc0xr94ETJKE-9TAA5XdqMpDwjrxk',
    appId: '1:543256822391:android:4a39aa99dc6562e044fc72',
    messagingSenderId: '543256822391',
    projectId: 'women-safety-app-30676',
    storageBucket: 'women-safety-app-30676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gl5UjtWIbw7C7_q6_Q-Ucn2bT1vbd7k',
    appId: '1:543256822391:ios:971c1a6c27c92f1644fc72',
    messagingSenderId: '543256822391',
    projectId: 'women-safety-app-30676',
    storageBucket: 'women-safety-app-30676.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gl5UjtWIbw7C7_q6_Q-Ucn2bT1vbd7k',
    appId: '1:543256822391:ios:971c1a6c27c92f1644fc72',
    messagingSenderId: '543256822391',
    projectId: 'women-safety-app-30676',
    storageBucket: 'women-safety-app-30676.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgW3Tp8pd2jX6iLZ983NofJfLhkEDaFj8',
    appId: '1:543256822391:web:83ce1a9c81bd030844fc72',
    messagingSenderId: '543256822391',
    projectId: 'women-safety-app-30676',
    authDomain: 'women-safety-app-30676.firebaseapp.com',
    storageBucket: 'women-safety-app-30676.firebasestorage.app',
    measurementId: 'G-9DTXW91P3W',
  );
}
